Repository hypertrons/hypertrons, pull requests merged in 2020-05, with the labels that each got.

#309 docs: add doc skeleton
  docs/_sidebar.md
  docs/architecture.md
  docs/index.html
  docs/plugin/core/configuration.md
  docs/plugin/core/event_manager.md
  docs/plugin/core/index.md
  docs/plugin/core/promise_handler_manager.md
  docs/plugin/core/scheduler_manager.md
  docs/plugin/external/hosting_platform.md
  docs/plugin/external/im.md
  docs/plugin/external/index.md
  docs/plugin/external/mail.md
  docs/plugin/external/translation.md
  docs/plugin/external/video_meeting.md
  docs/plugin/index.md
  docs/readme.md
Labels: area/document, pull/approved

#311 docs: add zh-cn doc skeleton
  docs/_coverpage.md
  docs/_navbar.md
  docs/index.html
  docs/zh-cn/_coverpage.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/architecture.md
  docs/zh-cn/plugin/core/configuration.md
  docs/zh-cn/plugin/core/event_manager.md
  docs/zh-cn/plugin/core/index.md
  docs/zh-cn/plugin/core/promise_handler_manager.md
  docs/zh-cn/plugin/core/scheduler_manager.md
  docs/zh-cn/plugin/external/hosting_platform.md
  docs/zh-cn/plugin/external/im.md
  docs/zh-cn/plugin/external/index.md
  docs/zh-cn/plugin/external/mail.md
  docs/zh-cn/plugin/external/translation.md
  docs/zh-cn/plugin/external/video_meeting.md
  docs/zh-cn/plugin/index.md
  docs/zh-cn/readme.md
Labels: area/document, pull/approved

#312 docs(deploy): add .nojekyll
  docs/zh-cn/.nojekyll
Labels: area/document, pull/approved

#313 docs: change homepage name.
  docs/CNAME
  docs/README.md
  docs/index.html
  docs/zh-cn/README.md
Labels: area/document, pull/approved

#315 docs: add docs for promise-handler and partial components
  app/plugin/ph-manager/ph-config.ts
  docs/component/approve.md
  docs/component/auto_label.md
  docs/component/command.md
  docs/component/label_setup.md
  docs/component/role.md
  docs/component/self_assign.md
  docs/plugin/core/promise_handler_manager.md
  docs/zh-cn/component/approve.md
  docs/zh-cn/component/auto_label.md
  docs/zh-cn/component/command.md
  docs/zh-cn/component/label_setup.md
  docs/zh-cn/component/role.md
  docs/zh-cn/component/self_assign.md
  docs/zh-cn/plugin/core/promise_handler_manager.md
  package-lock.json
Labels: area/document, pull/approved

#319 docs: add docs for translation plugin
  docs/plugin/external/translation.md
  docs/zh-cn/plugin/external/translation.md
Labels: area/document, pull/approved

#317 docs: add configuration/im/ci/complete_checklist/rerun docs
  docs/_sidebar.md
  docs/component/ci.md
  docs/component/complete_checklist.md
  docs/component/im.md
  docs/component/index.md
  docs/component/rerun.md
  docs/plugin/external/ci.md
  docs/plugin/external/index.md
  docs/plugin/index.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/component/ci.md
  docs/zh-cn/component/complete_checklist.md
  docs/zh-cn/component/im.md
  docs/zh-cn/component/index.md
  docs/zh-cn/component/rerun.md
  docs/zh-cn/plugin/core/configuration.md
  docs/zh-cn/plugin/external/ci.md
  docs/zh-cn/plugin/external/im.md
  docs/zh-cn/plugin/external/index.md
  docs/zh-cn/plugin/external/mail.md
  docs/zh-cn/plugin/external/video_meeting.md
  docs/zh-cn/plugin/index.md
Labels: area/document, pull/approved

#320 docs: add components sidebar
  docs/_sidebar.md
  docs/component/index.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/component/index.md
Labels: area/document, pull/approved

#316 add vote doc
  docs/_sidebar.md
  docs/component/index.md
  docs/component/vote.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/component/index.md
  docs/zh-cn/component/vote.md
Labels: area/document, pull/approved

#325 feat: add error-manager to handle errors uniformly
  app/plugin/error-manager/AppErrorManager.ts
  app/plugin/error-manager/ErrorManagerConfig.ts
  app/plugin/error-manager/app.ts
  app/plugin/error-manager/config/config.default.ts
  app/plugin/error-manager/package.json
  config/config.default.ts
  config/plugin.ts
  package-lock.json
  package.json
  test/plugin/error-manager/ErrorManager.test.ts
Labels: kind/bug, pull/approved

#328 docs: add summer 2020
  docs/_sidebar.md
  docs/event/summer2020.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/event/summer2020.md
Labels: area/document, pull/approved

#329 docs: modify summer 2020
  docs/event/summer2020.md
  docs/zh-cn/event/summer2020.md
Labels: area/document, pull/approved

#314 refactor: version-based config service
  app/basic/HostingPlatform/HostingBase.ts
  app/basic/HostingPlatform/HostingClientService/ConfigService.ts
  app/basic/HostingPlatform/HostingConfigBase.ts
  app/basic/HostingPlatform/HostingManagerBase.ts
  app/basic/HostingPlatform/event.ts
  app/basic/Utils.ts
  app/plugin/github/GitHubClient.ts
  test/plugin/basic/HostingPlatform/HostingClientBase.test.ts
  test/plugin/basic/HostingPlatform/HostingClientService/ConfigService.test.ts
  test/plugin/gitee/data/global-config.json
  test/plugin/github/GitHubTestUtil.ts
Labels: kind/enhancement, pull/approved
