Repository hypertrons/hypertrons, pull requests merged in 2020-02, with the labels that each got.

#254 feature: does not remind repliers of issues that contains specifc labels
  app/component/issue_reminder/config.ts
  app/component/issue_reminder/defaultConfig.ts
  app/component/issue_reminder/index.lua
  test/component/issue_reminder/issue_reminder.test.ts
Labels: kind/feature, pull/approved

#256 refactor: add community issue label
  .github/hypertrons.json
Labels: kind/enhancement, pull/approved

#260 doc: add cii badge
  README.md
Labels: area/document, pull/approved

#262 refactor: update the definition of issue_reminder config
  app/component/issue_reminder/config.ts
Labels: kind/enhancement, pull/approved

#266 refactor: add git hook check
  .gitignore
  .huskyrc
  .lintstagedrc
  commitlint.config.js
  package-lock.json
  package.json
Labels: kind/enhancement, pull/approved

#269 feat: add github action file
  .github/workflows/hypertrons.yml
  Jenkinsfile
  app/utils/md-lint/index.ts
  package.json
Labels: pull/approved

#270 refactor: add .component-history into .gitignore
  .gitignore
  app/basic/HostingPlatform/ComponentService.ts
Labels: kind/enhancement, pull/approved

#273 docs: add ci badge into README
  README.md
Labels: area/document, pull/approved

#276 refactor: fix configuration update bug, fix add repo bug
  app/basic/HostingPlatform/HostingClientService/ConfigService.ts
  app/plugin/github/GitHubApp.ts
  test/plugin/github/GitHubApp.test.ts
Labels: kind/bug, kind/enhancement, pull/approved

#278 docs: improve contributing guide (#268)
  CONTRIBUTING.md
Labels: area/document, pull/approved

#279 refactor: format repoData after receive event
  app/basic/DataTypes.ts
  app/basic/HostingPlatform/HostingClientService/RepoDataService.ts
  app/basic/HostingPlatform/event.ts
Labels: kind/enhancement, pull/approved

#280 refactor: disable remark-lint-no-dead-urls
  app/utils/md-lint/index.ts
Labels: kind/enhancement, pull/approved
